### ISSUE TITLE
Does it work with connective_signing_extension-1.0.6 ?

### ISSUE THREAD

**Issue by mcmate** [roelderickx/connective-plugin-linux#18] opened 2024-01-24 18:18 UTC
Connective signing extension 1.0.6 is the only one I can install from the Chrome web store https://chromewebstore.google.com/detail/connective-signing-extens/kclpjmhngbacampgcdojmiedamjbgjjm?utm_source=chrome-app-launcher-info-dialog Did not manage to install the xpi file, even with Foxified. With 1.0.6 it reports some errors though: "An error occured while handling your request." with no issues but no answer either when testing. Thank you for the help.

**Comment by roelderickx** [comment] 2024-01-24 21:16
I am not sure which extension you need for the site you are trying to log in with your eid, it can be either the Connective Browser Plugin or Connective SignId.
This repository is a replacement for the Connective Browser Plugin, not for Connective SignId which you are trying to install. It probably works similar but I currently don't have the time to investigate it.

**Comment by mcmate** [comment] 2024-01-24 22:52
But how do you install the connective_signing_extension-1.0.5.xpi of your
repository? When I open it with Google Chrome, it does not do more but
download the same file. And when trying to add it via Foxified, it
complains with some errors. Thank you in advance.

**Comment by roelderickx** [comment] 2024-01-25 16:26
Ok I see, in contrast to Firefox it is not possible to install xpi files in Chrome, unless you use the developer-mode workaround but then there are errors.
So I think the 1.0.6 version form the chrome web store is the one you'll need, I am able to install this extension without errors. But you seem to suggest there are errors while using the plugin then, I should look into the way it communicates with the backend.
I'll revert to you when I have more information.

**Comment by roelderickx** [comment] 2024-01-25 17:23
Question: do you use chrome or chromium? There seems to be a difference as to where the native messaging manifest must be installed. I'll have to add chromium to the nativemessaging-ng module anyway, I'll do that right away and release a new version.

**Comment by mcmate** [comment] 2024-01-25 22:14
Chrome.

**Comment by mcmate** [comment] 2024-01-25 22:15
Thank you in advance.

**Comment by roelderickx** [comment] 2024-01-27 10:16
On the Linux distro I work with Chrome is not available, I installed ubuntu on an old laptop and installed Chrome.

I can confirm the [Connective signing extension 1.0.6](https://chromewebstore.google.com/detail/connective-signing-extens/kclpjmhngbacampgcdojmiedamjbgjjm?utm_source=chrome-app-launcher-info-dialog) you mentioned is the right extension to install. I was also able to install the native messaging backend with the command `nativemessaging-install install chrome` and I can confirm the whole setup works for me.

However, I think you installed Chrome using a snap package, which is the suggested way to install software in ubuntu. The browser is then sandboxed, which is generally good from a security perspective since external applications cannot be executed, but that doesn't allow us to start the connective backend process either.

Work is ongoing to support native messaging in sandboxed browsers, see https://github.com/flatpak/xdg-desktop-portal/issues/655. Meanwhile I suggest installing Chrome by downloading manually from [the Google Chrome website](https://www.google.com/chrome/) and then install the package using the command `sudo dpkg -i google-chrome-stable_current_amd64.deb`.

**Comment by mcmate** [comment] 2024-01-29 08:46
In fact, I did install Chrome by downloading manually from the Google
Chrome website and followed the same procedure for the installation of the
plugin with no success as I described.

**Comment by roelderickx** [comment] 2024-01-29 09:31
Ok, then the installation of Chrome and the plugin are correct.

Can you go through [the troubleshoot guide](https://github.com/roelderickx/connective-plugin-linux/tree/main/test) and report in which step it is failing and which error messages you get?

**Comment by roelderickx** [comment] 2024-01-29 16:23
In that case the only component which doesn't work is the native messaging. The activation token is not verified by connective-plugin-linux, please see #12 for detailed information about this.

* Did you run `nativemessaging-install install chrome`? Also, make sure you run it from the directory where `native-manifest.json` can be found, ie the main directory of this repository.
* Did it succeed or were there any errors?
* Did it install the manifest file as `~/.config/google-chrome/NativeMessagingHosts/com.connective.signer.json`?
* If you open the installed manifest file, does the content of the path tag points to the backend? It must include the complete path.
* The browser needs to be restarted after installation or modification of the native messaging manifest

**Comment by mcmate** [comment] 2024-01-30 09:11
- I did make that error at the very beginning, but managed to get around
   running from the main directory of the repository indeed
   - In fact, when I run it as it was, I obtained this
   error: PermissionError: [Errno 13] Permission denied:
   '/home/oscar/.config/google-chrome/NativeMessagingHosts/com.connective.signer.json'
   Then I run it with sudo, but I obtained this error: FileNotFoundError:
   [Errno 2] No such file or directory:
   '/root/.config/google-chrome/NativeMessagingHosts'
   So in the end, I had to modify the
   file /usr/local/lib/python3.10/dist-packages/nativemessaging/install.py to
   change from the /root to the /home/oscar and succeeded
   This is the output of the execution:
       Reading manifest native-manifest.json
       Absolute path:
   /home/oscar/Downloads/connective-plugin-linux-main/connective-backend.py
       Saved manifest file to
   /home/oscar/.config/google-chrome/NativeMessagingHosts/com.connective.signer.json
   - And this it the installed manifest file (as you can see in the above
   mentioned folder):
   cat
   /home/oscar/.config/google-chrome/NativeMessagingHosts/com.connective.signer.json
   {"name": "com.connective.signer", "description": "Connective Extension",
   "path":
   "/home/oscar/Downloads/connective-plugin-linux-main/connective-backend.py",
   "type": "stdio", "allowed_origins":
   ["chrome-extension://kclpjmhngbacampgcdojmiedamjbgjjm/",
   "chrome-extension://iakejplkonnlkckfmnkmnjonjldbhpfa/",
   "chrome-extension://hjldggdfakblnppfaijhaioieincmlln/",
   "chrome-extension://fccadhkefgbjhhmhaifdjgabjjjhenek/",
   "chrome-extension://agapehmkpebacbgojngbpmcojkimlllf/"]}
   - And even after restarting, native messaging does not seem to work still

Thank you in advance

**Comment by roelderickx** [comment] 2024-01-30 17:57
Thanks for the extra information.

It seems strange you got a permission denied error on a subdirectory of your own home directory, it should not be necessary to run nativemessaging-install as root. Make sure the user who runs chrome (oscar in your case) has read permissions on `/home/oscar/.config/google-chrome/NativeMessagingHosts/com.connective.signer.json` and read+execute rights on `/home/oscar/Downloads/connective-plugin-linux-main/connective-backend.py`.

Apart from that I noticed the protocoltester does not work (anymore?) in Chrome. Also, ctrl-shift-J seems to be the same as F12 in Chrome, another difference with Firefox. Very annoying, I will have to add a separate tester for Chrome but it needs some study, I don't have that much time at the moment.

In stead you can test your setup if you start Chrome from a terminal window, so you see all output (the executable is called `google-chrome`). Then go to a website using the connective plugin, let's say [doccle](https://id.doccle.be/app/login) (click on log in with eid). You should start seeing the connective messages in the terminal window, even without connecting a card reader or providing you eid card.

If that doesn't happen, do you see any errors related to the connective plugin?

**Comment by mcmate** [comment] 2024-01-31 09:45
Thanks for the support.

Here is the output when starting Chrome from a terminal window (change part
of the info for <...>):

Card applet version: 17
Card 0x6C delay required: 0 ms
OUT {"readerList": [{"index": 0, "library": "__cardcomm__", "name": "Alcor
Micro AU9540 00 00", "atr": "3B9813400AA503010101AD1311", "cardPresent":
true, "cardType": 1}]}
IN {"cmd":"READ_FILE","reader":"Alcor Micro AU9540 00
00","fileId":"3F00DF014031","activationToken":"GYvQfXZ<...>KrSWIA==","isRequest":true}
Card applet version: 17
Card 0x6C delay required: 0 ms
OUT {"data": "010A423<...>1B001C00"}
IN {"cmd":"READ_FILE","reader":"Alcor Micro AU9540 00
00","fileId":"3F00DF014032","activationToken":"GYvQfXZ<...>KrSWIA==","isRequest":true}
Card applet version: 17
Card 0x6C delay required: 0 ms
OUT {"error": {"code": 5, "id": 5, "message": "Error reading file (Comm
0x6a87) (0xa4080c)"}}

**Comment by roelderickx** [comment] 2024-01-31 11:25
Ok, many thanks for the log.

It turns out to be the same problem as #15, but it wasn't resolved at the time because the user who reported the issue didn't need it anymore. As you can see the first READ_FILE call worked fine, but it fails at the second call. If you're lucky it will work for the second call as well next time, but it fails anyway before all files are read.
I am not sure but I think it is due to the fact the cardreader connects to the id card on each call, for your particular cardreader it may happen too fast.

I'll try to rework it without the superfluous connections, it is not too much work. I'll keep you updated, it would be appreciated if you can test 🙂

**Comment by mcmate** [comment] 2024-01-31 11:45
Perfect. I will wait for the update to test it. Thank you in advance.

**Comment by roelderickx** [comment] 2024-01-31 20:31
Can you try with the branch [issue19](https://github.com/roelderickx/connective-plugin-linux/tree/issue19) please?

I really hope it solves your problem, this is just a wild guess.

**Comment by mcmate** [comment] 2024-02-01 19:16
Unfortunately same error:

Card applet version: 17
Card 0x6C delay required: 0 ms
OUT {"readerList": [{"index": 0, "library": "__cardcomm__", "name": "Alcor
Micro AU9540 00 00", "atr": "3B9813400AA503010101AD1311", "cardPresent":
true, "cardType": 1}]}
IN {"cmd":"READ_FILE","reader":"Alcor Micro AU9540 00
00","fileId":"3F00DF014031","activationToken":"X3DzkFkfucXXPi<...>XdDyHTE0g==","isRequest":true}
OUT {"data": "010A4234<...>01A001B001C00"}
IN {"cmd":"READ_FILE","reader":"Alcor Micro AU9540 00
00","fileId":"3F00DF00503A","activationToken":"X3DzkFkfucXXPi<...>XdDyHTE0g==","isRequest":true}
OUT {"error": {"code": 5, "id": 5, "message": "Error reading file (Comm
0x6a87) (0xa4080c)"}}

(Well checked for the new version and restart of Google Chrome)
cat
/home/oscar/.config/google-chrome/NativeMessagingHosts/com.connective.signer.json
{"name": "com.connective.signer", "description": "Connective Extension",
"path":
"/home/oscar/Downloads/connective-plugin-linux-issue19/connective-backend.py",
"type": "stdio", "allowed_origins":
["chrome-extension://kclpjmhngbacampgcdojmiedamjbgjjm/",
"chrome-extension://iakejplkonnlkckfmnkmnjonjldbhpfa/",
"chrome-extension://hjldggdfakblnppfaijhaioieincmlln/",
"chrome-extension://fccadhkefgbjhhmhaifdjgabjjjhenek/",
"chrome-extension://agapehmkpebacbgojngbpmcojkimlllf/"]}

Thank you in advance.

**Comment by roelderickx** [comment] 2024-02-03 17:27
There seems to be a problem with the Alcor Micro AU9540, see LudovicRousseau/CCID#84. At the end Ludovic Rousseau points to https://ccid.apdu.fr/ccid/unsupported.html#0x058F0x9540, where it is stated that both readers are only partly supported.
However, I tested long time ago with an Alcor Micro AU 9560 (currently not in my possession) and it worked fine. Maybe the version of pyscard or ccid is different?
Or is the firmware different? It seems these readers are built-in with some HP and/or Lenovo laptops. Is that the case for you and do you have the possibility to download the latest firmware from their site to install it?

**Comment by mcmate** [comment] 2024-02-03 18:16
Ill try to check, but Im not sure the problem is on the reader side, since
I could log in in different services using it. Its just the
connective-plugin that I couldnt make it work. Could you specify the proper
pyscard or ccid versions maybe. My laptop is an Asus, so not sure I could
do much more.

**Comment by roelderickx** [comment] 2024-02-03 20:17
It is also strange that these kind of errors pop up now, in the past two years it never came up. Even for both Alcor Micro devices which are widespread.
So yes, it should be possible to make it work. I'll see if I can get one of these models to test with, to see if it works for a specific version of pyscard and/or ccid.

**Comment by mcmate** [comment] 2024-02-03 21:59
Perfect. Thank you.

**Comment by roelderickx** [comment] 2024-07-09 15:31
It seems to work with ubuntu 22, see #25.

**Comment by mcmate** [comment] 2024-07-10 08:38
nice, thank you

**Comment by roelderickx** [comment] 2024-07-10 10:18
Closing this issue as per the latest comment in #25.

Not sure if there is a solution without downgrading the whole OS, a docker image will almost certainly not receive any requests via the native messaging protocol.

**Closed by roelderickx** 2024-07-10 10:19 UTC

**Comment by mcmate** [comment] 2024-07-10 11:36
fair enough, mine was always ubuntu 22 though
